version: '3'
services:

  php74:
    container_name: php74
    build:
      context: .
      dockerfile: ./docker-files/PHP74.Dockerfile
    ports:
      - "8074:80"
    volumes:
      - ./www/php74:/var/www/html/

  php82:
    container_name: php82
    build:
      context: .
      dockerfile: ./docker-files/PHP82.Dockerfile
    ports:
      - "8082:80"
    volumes:
      - ./www/php82:/var/www/html/

  mariadb:
    container_name: mariadb
    image: mariadb:10.9.4
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mariadb-data:/var/lib/mariadb
    ports:
      - 3300:3306

  pgsql:
    container_name: pgsql
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./pgsql-data:/var/lib/pgsql
    ports:
      - 5400:5432

  # sqlsrv:
  #   container_name: sqlsrv
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   volumes:
  #     - ./sqlsrv-data:/var/lib/sqlsrv
  #   ports:
  #     - "1400:1433"
  #   environment:
  #     SA_PASSWORD: root
  #     ACCEPT_EULA: "Y"
